# Site settings
title: anas ijji
description: Just another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a>
baseurl: "/photo" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url: https://www.facebook.com/anas.stoune
github_url: https://leclairdelumier.github.io/new/
gitlab_url: 
googleplus_url: 
instagram_url: 

pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
